In [1]:
!pip install kora
from kora.selenium import wd

Collecting kora
  Downloading https://files.pythonhosted.org/packages/5b/0d/3d9ab9ee747f0925b038e8350ce137276a7a4730a96a3516485dc1b87ba3/kora-0.9.19-py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 4.7MB/s
Collecting fastcore
  Downloading https://files.pythonhosted.org/packages/d8/b0/f1fbf554e0bf3c76e1bdc3b82eedfe41fcf656479586be38c64421082b1b/fastcore-1.3.20-py3-none-any.whl (53kB)
     |████████████████████████████████| 61kB 5.7MB/s
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from kora) (5.5.0)
Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (from fastcore->kora) (19.3.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from fastcore->kora) (20.9)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (5.0.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (2.6.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (1.0.18)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (57.0.0)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython->kora) (0.8.1)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->fastcore->kora) (2.4.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect; sys_platform != "win32"->ipython->kora) (0.7.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from traitlets>=4.2->ipython->kora) (0.2.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->kora) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->kora) (1.15.0)
Installing collected packages: fastcore, kora
Successfully installed fastcore-1.3.20 kora-0.9.19

In [2]:
url = 'https://en.wikipedia.org/wiki/Road_safety_in_Europe'
wd.get(url)
wd.save_screenshot('screenshot.png');

In [7]:
import pandas as pd
tables = pd.read_html(wd.page_source)
tables[2]

           Country  ...  Number of Seriously Injured in 2017/2018[30]
0          Austria  ...                                  7,664 (2017)
1          Belgium  ...                                  3,757 (2017)
2         Bulgaria  ...                                  8,680 (2018)
3          Croatia  ...                                  2.776 (2018)
4           Cyprus  ...                                    348 (2018)
5          Czechia  ...                                  2,395 (2018)
6          Denmark  ...                                  1,756 (2017)
7          Estonia  ...                                    460 (2018)
8          Finland  ...                                    409 (2017)
9           France  ...                                 27,732 (2017)
10         Germany  ...                                 67,913 (2018)
11          Greece  ...                                     706 (748)
12         Hungary  ...                                  5,496 (2018)
13         Ireland  ...                                         966†d
14           Italy  ...                              17,309 (2017) †e
15          Latvia  ...                                    542 (2018)
16       Lithuania  ...                                     81 (2018)
17      Luxembourg  ...                                    256 (2017)
18           Malta  ...                                    317 (2018)
19     Netherlands  ...                                 20,800 (2017)
20          Poland  ...                                 10,963 (2018)
21        Portugal  ...                                  1,974 (2018)
22         Romania  ...                                  8,144 (2018)
23        Slovakia  ...                                  1,127 (2017)
24        Slovenia  ...                                    821 (2018)
25           Spain  ...                                  9,546 (2017)
26          Sweden  ...                                  4,200 (2018)
27  United Kingdom  ...                                 25,609 (2017)
28     EU 28 Total  ...                                           NaN

[29 rows x 11 columns]

In [21]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(wd.page_source,"html.parser")
table = soup.find_all('table')[2]
rows = table.find_all('tr')
row_list = list()

In [22]:
for tr in rows:
    td = tr.find_all('td')
    row = [i.text for i in td]
    row_list.append(row)

In [53]:
df_bs = pd.DataFrame(row_list,columns=['Country','Area','Population','GDP per capita','Population density','Vehicle ownership','Road Network Length','Total road deaths','Road deaths per Million Inhabitants','Number of people Killed by billion','Number of seriously Injurled'])
df_bs.set_index('Country',inplace=True)
df_bs.drop(['Road Network Length','Number of people Killed by billion','Number of seriously Injurled'],  inplace=True, axis=1)
df_bs['Year'] = '2018'
df_bs.sort_values(by="Road deaths per Million Inhabitants",ascending=False,kind="mergesort")
df_bs.to_csv('test.csv')